use shared::{print_h2, print_h3};

// ------------------- Simple macros -------------------

macro_rules! say_hello {
    () => {
        println!("Hello from a macro!");
    };
}

macro_rules! double {
    ($x:expr) => {
        $x * 2
    };
}

// ------------------- Multiple patterns -------------------

macro_rules! describe {
    () => {
        println!("No arguments given.");
    };
    ($val:expr) => {
        println!("Got: {:?}", $val);
    };
    ($val:expr, $label:expr) => {
        println!("{}: {:?}", $label, $val);
    };
}

// ------------------- Designators -------------------
// expr   - expression
// ident  - identifier (variable/function name)
// ty     - type
// stmt   - statement
// pat    - pattern
// path   - module path (e.g. std::collections::HashMap)
// block  - { ... } block
// item   - item (fn, struct, enum, ...)
// tt     - token tree (catch-all)
// literal - literal value
// vis    - visibility qualifier

macro_rules! create_fn {
    ($fn_name:ident) => {
        fn $fn_name() {
            println!(
                "Function '{}' was generated by macro.",
                stringify!($fn_name)
            );
        }
    };
}

// ------------------- Repetition -------------------
// $(...)* = zero or more
// $(...)+ = one or more
// $(...)? = zero or one
// Separator goes between $(...) and the quantifier: $($x:expr),*

// $(,)? allows an optional trailing comma (e.g. my_vec![1, 2, 3,] is valid).
// The outer {{ }} creates a block expression so the macro can use let bindings
// and return a value as the block's final expression.
macro_rules! my_vec {
    ($($elem:expr),* $(,)?) => {{
        #[allow(unused_mut)]
        let mut v: Vec<_> = Vec::new();
        $(v.push($elem);)*
        v
    }};
}

macro_rules! sum {
    ($($val:expr),+ $(,)?) => {{
        let mut total = 0;
        $(total += $val;)+
        total
    }};
}

// ------------------- Struct generation -------------------

macro_rules! make_struct {
    ($name:ident { $($field:ident : $ty:ty),* $(,)? }) => {
        struct $name {
            $($field: $ty,)*
        }
    };
}

// ------------------- Recursive macro -------------------

macro_rules! count_items {
    () => { 0usize };
    ($head:expr $(, $tail:expr)*) => {
        1usize + count_items!($($tail),*)
    };
}

// ------------------- TT muncher -------------------
// Processes tokens one at a time via recursion.
// The base case () ends recursion; each step peels off $first and recurses with $rest.
// This pattern is used when you can't express the logic with simple repetition alone.

macro_rules! print_all {
    () => {};
    ($first:expr $(, $rest:expr)*) => {
        println!("{:?}", $first);
        print_all!($($rest),*);
    };
}

// ------------------- stringify! and concat! -------------------

macro_rules! make_greeting {
    ($name:ident) => {
        concat!("Hello, ", stringify!($name), "!")
    };
}

create_fn!(generated_function);
make_struct!(Point { x: f64, y: f64 });

pub fn run() {
    print_h2!("Declarative Macros");

    print_h3!("Basic invocation");
    say_hello!();
    say_hello![]; // [] style is also valid
    say_hello! {}; // {} style is also valid

    let result: i32 = double!(21);
    println!("double!(21) = {}", result);

    print_h3!("Multiple patterns");
    describe!();
    describe!(42);
    describe!(42, "answer");
    describe!("hello", "greeting");

    print_h3!("Designators");
    generated_function(); // defined by create_fn! above

    print_h3!("Repetition");
    let v: Vec<i32> = my_vec![1, 2, 3, 4, 5];
    println!("my_vec![1,2,3,4,5] = {:?}", v);
    let empty: Vec<i32> = my_vec![];
    println!("my_vec![] = {:?}", empty);

    let total: i32 = sum!(1, 2, 3, 4, 5);
    println!("sum!(1,2,3,4,5) = {}", total);

    print_h3!("Recursive macros");
    let count: usize = count_items!(10, 20, 30, 40);
    println!("count_items!(10,20,30,40) = {}", count);
    let zero: usize = count_items!();
    println!("count_items!() = {}", zero);

    print_h3!("TT muncher");
    print_all!(1, "hello", 3.14, true);

    print_h3!("stringify! / concat!");
    let tokens: &str = stringify!(x + y * z); // turns token stream into &str literal
    println!("stringify!(x + y * z) = \"{}\"", tokens);

    let greeting: &str = make_greeting!(World);
    println!("make_greeting!(World) = \"{}\"", greeting);

    print_h3!("Struct generation");
    let p: Point = Point { x: 1.0, y: 2.0 };
    println!("Point {{ x: {}, y: {} }}", p.x, p.y);

    print_h3!("Macro hygiene");
    // Variables introduced inside a macro don't escape into caller scope
    macro_rules! hygienic {
        ($val:expr) => {{
            let inner: i32 = $val * 2; // 'inner' is invisible outside this block
            inner
        }};
    }
    let doubled: i32 = hygienic!(10);
    println!("hygienic!(10) = {}", doubled);
    // ERROR: println!("{}", inner); // 'inner' not in scope here
}
